server:
  port: 8081

spring:
  application:
    name: email-notifications-listener
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://root:example@mongo:27017/notifications-db?authSource=admin


